### ISSUE TITLE
Sigil sign inside code block breaks everything

### ISSUE THREAD

**Issue by somedude3141** [joakin/markdown-folder-to-html#16]
Thanks for this simple and elegant library.

This breaks down the rendering:

```php
'$KEY$' => $VALUE$,
```

If I remove the `$` everything works again.

**Comment by joakin** [comment]
Oh wow, weird bug!

**Comment by joakin** [comment]
Nice catch, it was because of the use of `String.prototype.replace` with the content with `$'`. Very interesting!

I learnt a lot more about the replacement patterns: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace#Specifying_a_string_as_a_parameter

I've released 1.7.0 with the fix. You can see it working here https://chimeces.com/markdown-folder-to-html/tests/issue16.html
