### ISSUE TITLE
Use highlight option markdow-it

### ISSUE THREAD

**Issue by valentinbdv** [joakin/markdown-folder-to-html#30]
As you can see in markdown-it example page (https://markdown-it.github.io), you can check the highlight option which gives more details in code blocks.

Could you add that in this great project, please? ;)

**Comment by joakin** [comment]
I believe I didn’t include it before because it would mean that this project would have to depend on highlight.js, and this is possible client side when customizing the template. There are also other highlighting options so I didn’t want to make a choice for the user. More on that 

Depending on the library means that for getting bug fixes and new language highlighting a user would have to npm update to update the dependency ([docs](https://github.com/markdown-it/markdown-it#syntax-highlighting), or in the worst case of a major version we would have to upgrade the dependency and release a new version of this tool (subjecting this project to maintenance burden and version churn).

In this case it seems like they have been at 9.X for a long time (since 2015) so it is likely the npm update route for most users. See

https://github.com/highlightjs/highlight.js/releases

For documentation purposes, see https://highlightjs.org/ where it shows how easy it is to include this on the HTML file.

We have #20 open which suggests one way to do it, and this one with highlight is another.

I’m going to post some thoughts on the other thread 🧵, please chime in there.

**Comment by joakin** [comment]
Sorry, we have #14 as the main task, #20 is the other option which is closed.

Let’s continue this in #14
